<form>
	<button type="button" class="c_ajaxcall">Ajax Call</button>
	<p class="response_result"></p>
</form>

<script>
  requirejs([
  	'jquery'
  	],function($){
    	$(document).ready(function(){
	        $(document).on('click','.c_ajaxcall',function(){
	        	var base = '<?php echo $block->getBaseUrl(); ?>'
	        	var url = base+"admin/ugtest/index/ajaxcall"
	        	$.ajax({
			        url: url,
			        type: "Post",
					data: {id : 1}, //exemple
					dataType: 'json',
			        success: function (response) {
			           console.log(response)
			           $('.response_result').html(response.ajaxcall)
			        }
			    }); 
	        })
	    })


  });
</script>